language: erlang
before_install:
        - sudo apt-get install libpam0g-dev libexpat1-dev
        - tools/travis-generate-pass.sh
        - tools/travis-check-tests-branch.sh
install: tools/travis-build.sh
before_script:
        - tools/travis-setup-db.sh
script: tools/travis-test.sh

after_success:
        - tools/travis-upload-release.sh

after_script:
        - cat `ls -1 -d -t apps/ejabberd/logs/ct_run* | head -1`/apps.ejabberd.logs/run.*/suite.log
        - tail -100 dev/mongooseim_node1/log/ejabberd.log
        - if [ -s dev/mongooseim_node1/log/crash.log ]; then cat dev/mongooseim_node1/log/crash.log; fi
        - cat `ls -1 -d -t test/ejabberd_tests/ct_report/ct_run.* | head -1`/ejabberd_tests.*/run.*/suite.log
        - cat dev/mongooseim_node1/etc/ejabberd.cfg
services: redis-server
branches:
        only:
                - master
                - dev
notifications:
        email: lvzecai@gmail.com
otp_release:
        - 17.1
env:
        global:
                - TARBALL_NAME=mongooseim_${TRAVIS_COMMIT:0:6}.tar.gz
                - TEST_CONFIG=odbc_redis
                - DB=mysql
        matrix:
                - SPEC=embedded
                - SPEC=spec1
                - SPEC=spec2
                - SPEC=spec3
                - SPEC=spec4
                - SPEC=spec5
                - SPEC=spec5
                - SPEC=spec6
